### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by pvcarroll** [DigitalInclusion/digitalatx#3]
RGB codes
Banner BG: R147, G212, B239
Menu Strip: R39, G170, B224
Sidebar: R39, G170, B224
Font/Type: R0, G85, B129
1. Homepage (JT)
2. Location profile page (JT)
3. Add location form layout (Paul - awaiting design)
4. Maps
   - Are there two places with a map, the Mapping page and an embedded map on the location profile page?
   - Should these maps be the same except the Mapping page map has all the locations and the profile page map has only its location?
     There will just be one Mapping page, with the map embedded from CartoDB. Down the road we might set-up integration with the location profiles pages, but to keep things simple and get it off the ground quickly, I’m planning to manage these individually. For more context, the mapping page is really meant to show where gaps in service and opportunity areas are when compared to our data about Internet usage and home Internet access.
5. CMS blogging
   - Will this be for comments on the profile page and the storytelling page?
   - I remember talking about it but I forget the intention for those two features.
     Comments on the profile page are separate from the Storytelling/Blogging page. The comments are meant for nonprofits to share opportunities/challenges related to specific programs or locations—these will be restricted to logged in users only. 

The blogging feature will be totally public and will be a place where nonprofits can write a brief article about a trend or an event related to their organization. The purpose of this is to allow organizations to share more about what they are working on with each other and with the community as a whole.
1. Migration to city servers
   - Does anything else depend on this?
   - Should we do this before the CMS integregration?
     I think we might need to talk this through, as I’m a little fuzzy on integrations. 

Dev work for later:
1. users
2. authentication

**Comment by 100stacks** [comment]
Great idea to add all items as issues!  I am going to break out each numbered item into separate issues for higher fidelity tracking.

**Comment by pvcarroll** [comment]
I think we have open issues for the remaining items.
