### ISSUE TITLE
Open Austin Ship It weekend

### ISSUE THREAD

**Issue by sharlalikesyou** [DigitalInclusion/digitalatx#9]
• UX/UI design needed for Lab Profile pages
• Add Editing capabilities to  Lab Profile pages
• Add search functionality on Location Inventory page for zipcode & organization
• Build blogging interface for "Storytelling" page
• Add user/credential functionality
• User testing, particularly on mobile and different browsers

**Comment by pvcarroll** [comment]
I should definitely be able to add the other search options on the Location
Inventory page next weekend.
Probably some other stuff too.

**Comment by pvcarroll** [comment]
Moved unfinished items into separate work items
